### ISSUE TITLE
ImportError: No module named customxml  after I had pybrain installed!

### ISSUE THREAD

**Issue by SeekPoint** [TakuyaHiraoka/Dialogue-State-Tracking-using-LSTM#2]
rzai@rzai00:~/prj$ sudo pip install pybrain
Downloading/unpacking pybrain
  Downloading PyBrain-0.3.tar.gz (262kB): 262kB downloaded
  Running setup.py (path:/tmp/pip_build_root/pybrain/setup.py) egg_info for package pybrain

Installing collected packages: pybrain
  Running setup.py install for pybrain

  Could not find .egg-info directory in install record for pybrain
Successfully installed pybrain
Cleaning up...
rzai@rzai00:~/prj$ cd Dialogue-State-Tracking-using-LSTM/
rzai@rzai00:~/prj/Dialogue-State-Tracking-using-LSTM$ cd dstc4_traindev/
rzai@rzai00:~/prj/Dialogue-State-Tracking-using-LSTM/dstc4_traindev$ python main.py 
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    from LSTMWithBOW import LSTMWithBOWTracker
  File "/home/rzai/prj/Dialogue-State-Tracking-using-LSTM/dstc4_traindev/scripts/LSTMWithBOW.py", line 19, in <module>
    from pybrain.tools.customxml import NetworkWriter, NetworkReader
ImportError: No module named customxml
rzai@rzai00:~/prj/Dialogue-State-Tracking-using-LSTM/dstc4_traindev$

**Comment by TakuyaHiraoka** [comment]
Hi, 
Actually Pybrain-0.3 does not support customxml, so you need the latest version (Pybain-0.3.3). 
You can download its source code at following link: 
https://github.com/pybrain/pybrain

**Comment by SeekPoint** [comment]
fixed,thanks!
